### ISSUE TITLE
Error - no bucket for users

### ISSUE THREAD

**Issue by gzzglc89** [LassoProject/lasso#19]
When I try to authenticate a user I have this error:

ERRO[0014] no bucket for users
ERRO[0014] key required
2018/09/05 23:20:59 http: panic serving 127.0.0.1:57072: interface conversion: interface is nil, not string
goroutine 11 [running]:
net/http.(*conn).serve.func1(0xc420055600)
	/usr/lib/go/src/net/http/server.go:1491 +0x12a
panic(0x8a1c00, 0xc420012e40)
	/usr/lib/go/src/runtime/panic.go:458 +0x243
github.com/LassoProject/lasso/handlers.CallbackHandler(0xb3af00, 0xc42010fad0, 0xc4200b2b40)
	/root/go/src/github.com/LassoProject/lasso/handlers/handlers.go:414 +0x894
net/http.HandlerFunc.ServeHTTP(0x960320, 0xb3af00, 0xc42010fad0, 0xc4200b2b40)
	/usr/lib/go/src/net/http/server.go:1726 +0x44
github.com/LassoProject/lasso/pkg/timelog.TimeLog.func1(0xb3af00, 0xc42010fad0, 0xc4200b2a50)
	/root/go/src/github.com/LassoProject/lasso/pkg/timelog/timelog.go:33 +0x14b
net/http.HandlerFunc.ServeHTTP(0xc42012b660, 0xb3af00, 0xc42010fad0, 0xc4200b2a50)
	/usr/lib/go/src/net/http/server.go:1726 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420136780, 0xb3af00, 0xc42010fad0, 0xc4200b2a50)
	/usr/lib/go/src/net/http/server.go:2022 +0x7f
net/http.serverHandler.ServeHTTP(0xc420054b80, 0xb3af00, 0xc42010fad0, 0xc4200b2a50)
	/usr/lib/go/src/net/http/server.go:2202 +0x7d
net/http.(*conn).serve(0xc420055600, 0xb3b780, 0xc420139400)
	/usr/lib/go/src/net/http/server.go:1579 +0x4b7
created by net/http.(*Server).Serve
	/usr/lib/go/src/net/http/server.go:2293 +0x44d

**Comment by bnfinet** [comment]
@aaronpk is this similar to the error you saw a few weeks ago?

@gzzglc89 my fuzzy recollection of @aaronpk's issue was that this occurred once the first time lasso was authenticated against and then it went away.  Is this the case with your error?

**Comment by bnfinet** [comment]
FYI we're often in the IRC channel #lasso on freenode and can offer some support there

**Comment by gzzglc89** [comment]
@bnfinet I have this error every time I try to authenticate the user, not only the first time.

**Comment by aaronpk** [comment]
I had this problem too at one point. IIRC I did something like delete the SQLite database and start over and it started working. I wasn't able to figure out the actual underlying issue.

**Comment by bnfinet** [comment]
@gzzglc89 did that resolve the issue for you?

**Comment by gzzglc89** [comment]
@bnfinet it did not resolve but I'm using another way to authenticate so this is not needed
