### ISSUE TITLE
Invalid session state

### ISSUE THREAD

**Issue by i8ramin** [LassoProject/lasso#21]
Hi. Trying to use this library and having some issues. Getting the following error message and not sure what it means.

```
> map[] 192.168.96.3:32998 /auth <nil> <nil> <nil> 0xc420155480}\n"
auth_1   | time="2018-09-10T02:28:33Z" level=debug msg=/auth
auth_1   | time="2018-09-10T02:28:33Z" level=error msg="Invalid session state: stored %!s(<nil>), returned "
auth_1   | time="2018-09-10T02:28:33Z" level=debug msg="Request handled successfully"
auth_1   | time="2018-09-10T02:28:33Z" level=debug msg="statuscode: <nil>"
```

Here is the repo I am working from: https://github.com/i8ramin/nginx-lasso

**Comment by i8ramin** [comment]
never mind, issue on my end. resolved it.

**Comment by bnfinet** [comment]
So glad to hear that you were able to get it working.  Could you elaborate slightly on the nature of the fix?  It might be helpful for others when encountering this error.

**Comment by i8ramin** [comment]
I was hitting the wrong endpoint for the initial auth_request call. Here is the diff of the change -- https://github.com/i8ramin/nginx-lasso/commit/0c4e3e5c01447a2db9a56b8403d9d4779e3ebfee

So now the oauth2 handshake seems to be happening correctly, but I am facing another issue where I am not able to login or the system doesn't recognize that I am logged in, so I keep getting redirected to the oidc providers login screen. Still trying to figure that part out.

**Comment by bnfinet** [comment]
Thanks so much for adding that context.
