### ISSUE TITLE
use username instead of email for github and github enterprise

### ISSUE THREAD

**Issue by bnfinet** [LassoProject/lasso#23]
as per #22 there is an issue if user did not publish the email so that the API return null for email field

instead, use the `username` in the JWT

**Comment by bnfinet** [comment]
thanks to @QingsongYao for discovering this bug

**Comment by bnfinet** [comment]
@QingsongYao pretty sure the work on #16 fixed this, could you confirm?

**Comment by QingsongYao** [comment]
Sure,  I will install and confirm it works. I wonder do we have a new docker image pushed or I will build one locally.

**Comment by bnfinet** [comment]
thanks so much @QingsongYao 

the Docker build for https://hub.docker.com/r/bfoote/lasso/ is triggered by a push to the old repo at github.com/bnfinet/lasso

When we moved to github.com/LassoProject/lasso the trigger for the docker hub build apparently got severed.

I've setup https://hub.docker.com/r/lassoproject/lasso as a new Automated Build and also reestablished https://hub.docker.com/r/bfoote/lasso along with a note that we've moved to the lassoproject/lasso docker hub repo
