### ISSUE TITLE
The name "Lasso" is already taken by our own library

### ISSUE THREAD

**Issue by pcros** [LassoProject/lasso#35]
Hi,

I work for a french company, Entr'ouvert, and we developped, since 2003, a SAML library called Lasso : http://lasso.entrouvert.org/

It has been SAML 2 certified by the liberty Alliance consortium in 2006, it is packaged in Debian, Red Hat, etc. and used by third party projects such as mod_mellon, developed by Uninett in Norway.

It is also used by customers like Cisco, Bloomberg, Miracl and most french universities.

You can easily understand we fear confusion as your project has taken the same name, also in the SSO domain.

For a clear identification of both projects, we'd like to ask you if you could switch your project to something different?

Thank you,

**Comment by bnfinet** [comment]
Thanks for reaching out.

We are in the process of renaming "lasso" to "vouch" and will move the repository to https://github.com/vouch/vouch

If you or your customers who are using `nginx` should ever need to secure their private sites with OAuth2/OIDC please do consider letting them know about **vouch**.

**Comment by pcros** [comment]
Hi,

Good news.

Thank you and long live Vouch!
