### ISSUE TITLE
[FEATURE REQ] google authenticator?

### ISSUE THREAD

**Issue by saveyour** [LassoProject/lasso#37]
is there a way to use lasso to authenticate with the offline google authenticator tokens (like from the android app) ?

i see it has the ability to use google's OAUTH but it would be great if it could allow users to login by using the password generated from the app. 

thanks!

**Comment by saveyour** [comment]
i would like to use google authenticator's 2FA feature without having to rely on passing data between the google servers and my servers. some users may not wish to have their personal google accounts associated with particular website they visit (via the SSO mechanism) so it would add much value by giving privacy-concerned people an option as well. thanks!

**Comment by bnfinet** [comment]
You may care to look at Key Cloak..

https://www.keycloak.org/docs/3.3/server_admin/topics/authentication/otp-policies.html

After installing Key Cloak you'll have an hotp capable idp.  You can then setup lasso to use your Key Cloak as the oauth oidc provider.

There are a few other idps which might meet your criteria....

https://github.com/privacyidea/privacyidea/blob/master/README.rst

If you need help with that setup, please do let me know.
