### ISSUE TITLE
multiple redirects.. I think I know why.. but confirming

### ISSUE THREAD

**Issue by cmollis** [LassoProject/lasso#38]
so, over the weekend, i was able to get this (sorta) working with Okta.. I'm now getting the callback from okta..but it doesn't look like the JWT is set properly on the domain, so it goes into a redirect loop (with okta).  I think it's because I don't have an actual live domain for the lasso service so it doesn't set the JWT correctly (but I'm not sure).  Here is the output from lasso:

ERRO[0015] no jwt found in request
INFO[0015] | 401 |  120.372µs /validate      avgLatency=66.802768ms host="127.0.0.1:9090" ipPort="127.0.0.1:49242" latency=" 120.372µs" method=GET path=/validate referer= request=7 statusCode=401
INFO[0015] | 302 |  242.791µs /login         avgLatency=58.482771ms host=ec2-18-234-210-151.compute-1.amazonaws.com ipPort="127.0.0.1:49244" latency=" 242.791µs" method=GET path=/login referer= request=8 statusCode=302
INFO[0015] OpenID userinfo body:  {"sub":"00u9cpj0gaOBYVZ4v0h7","email":"chris.mollis@gmail.com","email_verified":true}
INFO[0015] | 302 | 208.432955ms /auth        avgLatency=75.143902ms host=ec2-18-234-210-151.compute-1.amazonaws.com ipPort="127.0.0.1:49246" latency=208.432955ms method=GET path=/auth referer= request=9 statusCode=302
ERRO[0015] no jwt found in request
INFO[0015] | 401 |   71.296µs /validate      avgLatency=67.636642ms host="127.0.0.1:9090" ipPort="127.0.0.1:49248" latency="  71.296µs" method=GET path=/validate referer= request=10 statusCode=401
INFO[0015] | 302 |  256.479µs /login         avgLatency=61.511173ms host=ec2-18-234-210-151.compute-1.amazonaws.com ipPort="127.0.0.1:49250" latency=" 256.479µs" method=GET path=/login referer= request=11 statusCode=302
INFO[0016] OpenID userinfo body:  {"sub":"00u9cpj0gaOBYVZ4v0h7","email":"chris.mollis@gmail.com","email_verified":true}

Initially nginx redirects to /auth (lasso), which redirects to Okta.  I log into okta, and then it redirects back to /auth (lasso), which appears to extract my user info (I had thought from the JWT), but errors with no JWT found, which redirects to /validate back to /login back to Okta, which redirects back to /auth.. yada yada.

If you remember, I'm somewhat faking the 'lasso.mydomain.com' with a proxy set up on a different port, but the same domain.  here:

server {
  listen 81 ;
  server_name ec2-18-234-210-151.compute-1.amazonaws.com;

  #location / {
   #         root   html;
    #        index  index.html index.htm;
     #   }

  #ssl_certificate /etc/letsencrypt/live/login.avocado.lol/fullchain.pem;
  #ssl_certificate_key /etc/letsencrypt/live/login.avocado.lol/privkey.pem;

  # Proxy to your Lasso instance
  location / {
    proxy_set_header  Host  ec2-18-234-210-151.compute-1.amazonaws.com;
    proxy_set_header  X-Forwarded-Proto http;
    proxy_pass        http://127.0.0.1:9090;
  }
}

instead of:

server {
    listen 80 default_server;
    server_name lasso.yourdomain.com;
    location / {
       proxy_set_header Host lasso.yourdomain.com;
       proxy_pass http://127.0.0.1:9090;
    }
}

there's a note about setting the setting the proxy header or the jwt isn't set correctly.. (this JWT is probably managed by lasso itself).

**Comment by bnfinet** [comment]
I'm going to close this and move us back to #36
