### ISSUE TITLE
Can tagged builds be turned on?

### ISSUE THREAD

**Issue by mikebryant** [LassoProject/lasso#39]
In the automated build configuration, add a section to match all tags. This would allow us to have builds of releases, instead of having to follow a moving target.

**Comment by bnfinet** [comment]
Do you mean the docker automated build on docker hub?

**Comment by mikebryant** [comment]
Yes

**Comment by bnfinet** [comment]
I've adjusted the docker build settings to include tags
https://hub.docker.com/r/lassoproject/lasso/~/settings/automated-builds/

I'll close the issue after the next tag push and confirming the tagged docker image build for `lassoproject/lasso:0.2.13`

Just curious, have you noticed a regression or something in particular that informs your request?

**Comment by mikebryant** [comment]
Oh, no, not noticed any issues. I'm wanting to use it for work purposes and we've got a policy about never using latest, always pinning versions for reproducibility.

I thought it was worth asking because with automated builds it's easy to enable :) 

Thanks for changing this :)

**Comment by bnfinet** [comment]
np, easily done.

While I've got your attention, can I ask if your org uses `HEALTHCHECK` in its docker infra?  I'm looking ahead at adding a `/healthcheck` endpoint (just ping/heartbeat initially).  Would HEALTHCHECK in the Dockerfile be of use to your org?

**Comment by mikebryant** [comment]
We run kubernetes. An endpoint like that would be useful for kubernetes readiness or liveness probes, though the HEALTHCHECK command itself would be ignored by our infrastructure

**Comment by bnfinet** [comment]
its building as `lassoproject/lasso:v0.2.13`

I've adjusted the tags to be `lassoproject/lasso:0.2.13` instead as per..
https://stackoverflow.com/questions/25328166/docker-hub-automated-build-tagging

**Comment by bnfinet** [comment]
works! https://hub.docker.com/r/lassoproject/lasso/builds/
