### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by joshkay** [LassoProject/lasso#44]
I have been trying to get this up and running for the last couple of days, but have been unsuccessful.  Can someone point out what I am doing wrong?

I am running lasso in docker and encounter a 502 error when I am redirected to the lasso login.  I am trying to authenticate using nginx.  It looks like the none of the upstream variables are being set properly, but I am quite new to this area.

```
time="2018-12-29T11:36:44-05:00" level=debug msg=/validate
time="2018-12-29T11:36:44-05:00" level=error msg="no jwt found in request"
time="2018-12-29T11:36:44-05:00" level=debug msg="CaptureWriter.WriteHeader set w.StatusCode 401"
time="2018-12-29T11:36:44-05:00" level=debug msg="Request handled successfully: 401"
time="2018-12-29T11:36:44-05:00" level=info msg="|401|   86.556µs /validate" avgLatency=" 179.024µs" host="192.168.10.32:9090" ipPort="172.26.0.1:35670" latency="  86.556µs" method=GET path=/validate referer= request=4 statusCode=401 time="2018-12-29T11:36:44-05:00" level=debug msg="Request received : &{GET /login?url=https://REDACTED_URL/&lasso-failcount=&X-Lasso-Token=&error= HTTP/1.0 1 0 map[Upgrade-Insecure-Requests:[1] User-Agent:[Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36] Accept:[text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8] Accept-Encoding:[gzip, deflate, br] Accept-Language:[en-CA,en;q=0.9,fr;q=0.8,en-GB;q=0.7,en-US;q=0.6] X-Forwarded-Proto:[https] Connection:[close]] {} <nil> 0 [] true login.REDACTED_URL map[] map[] <nil> map[] 172.26.0.1:35674 /login?url=https://REDACTED_URL/&lasso-failcount=&X-Lasso-Token=&error= <nil> <nil> <nil> 0xc42018cf40}"
time="2018-12-29T11:36:44-05:00" level=debug msg=/login
time="2018-12-29T11:36:44-05:00" level=debug msg="session state set to t2G6AkxdPzmt0gLkakXEzWfefpZvYrwoE/roTARSOdU=" time="2018-12-29T11:36:44-05:00" level=debug msg="session requestedURL set to https://REDACTED_URL/"
time="2018-12-29T11:36:44-05:00" level=debug msg="saving session"
2018/12/29 11:36:44 http: panic serving 172.26.0.1:35674: runtime error: invalid memory address or nil pointer dereference
goroutine 21 [running]:
net/http.(*conn).serve.func1(0xc420081b80)
        /usr/local/go/src/net/http/server.go:1726 +0xd0
panic(0x8be1c0, 0xbf58b0)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/LassoProject/lasso/handlers.loginURL(0xc4201ca000, 0xc420084cc0, 0x2c, 0xc420181120, 0x0)
        /go/src/github.com/LassoProject/lasso/handlers/handlers.go:62 +0x40
github.com/LassoProject/lasso/handlers.LoginHandler(0x9ae8a0, 0xc420181120, 0xc4201ca000)
        /go/src/github.com/LassoProject/lasso/handlers/handlers.go:296 +0x7ad
net/http.HandlerFunc.ServeHTTP(0x96bee0, 0x9ae8a0, 0xc420181120, 0xc4201ca000)
        /usr/local/go/src/net/http/server.go:1947 +0x44
github.com/LassoProject/lasso/pkg/timelog.TimeLog.func1(0x9af5e0, 0xc420130700, 0xc42012be00)
        /go/src/github.com/LassoProject/lasso/pkg/timelog/timelog.go:47 +0x17b
net/http.HandlerFunc.ServeHTTP(0xc4200f3fa0, 0x9af5e0, 0xc420130700, 0xc42012be00)
        /usr/local/go/src/net/http/server.go:1947 +0x44
net/http.(*ServeMux).ServeHTTP(0xc420171dd0, 0x9af5e0, 0xc420130700, 0xc42012be00)
        /usr/local/go/src/net/http/server.go:2340 +0x130
net/http.serverHandler.ServeHTTP(0xc42017b040, 0x9af5e0, 0xc420130700, 0xc42012be00)
        /usr/local/go/src/net/http/server.go:2697 +0xbc
net/http.(*conn).serve(0xc420081b80, 0x9afca0, 0xc42018cec0)
        /usr/local/go/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
        /usr/local/go/src/net/http/server.go:2798 +0x27b
```

Here is my relevant nginx config:

```
server {
    listen 443 ssl;
    server_name login.REDACTED_URL;

    ssl_certificate /etc/letsencrypt/live/login.REDACTED_URL/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/login.REDACTED_URL/privkey.pem;

    # Proxy to your Lasso instance
    location / {
      proxy_set_header  Host  login.REDACTED_URL;
      proxy_set_header  X-Forwarded-Proto https;
      proxy_pass        http://127.0.0.1:9090;
    }
  }

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name REDACTED_URL;

    ssl_certificate /etc/letsencrypt/live/REDACTED_URL/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/REDACTED_URL/privkey.pem;

    # Any request to this server will first be sent to this URL
    auth_request /validate;

    location = /validate {
      # lasso can run behind the same nginx-revproxy
      # May need to add "internal", and comply to "upstream" server naming
      proxy_pass http://127.0.0.1:9090/validate;

      # lasso only acts on the request headers
      proxy_pass_request_body off;

      proxy_set_header Content-Length "";
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;

      # pass X-Lasso-User along with the request
      #auth_request_set $auth_resp_x_lasso_user $upstream_http_x_lasso_user;

      # these return values are used by the @error401 call
      auth_request_set $auth_resp_jwt $upstream_http_x_lasso_jwt;
      auth_request_set $auth_resp_err $upstream_http_x_lasso_err;
      auth_request_set $auth_resp_failcount $upstream_http_x_lasso_failcount;
    }

    # if validate returns `401 not authorized` then forward the request to the error401block
    error_page 401 = @error401;

    location @error401 {
        # redirect to lasso for login
        return 302 https://login.REDACTED_URL/login?url=$scheme://$http_host$request_uri&lasso-failcount=$auth_resp_failcount&X-Lasso-Token=$auth_resp_jwt&error=$auth_resp_err;
    }

    location / {
      
    }

    root /usr/share/nginx/html;
    index index.html;
  }
```

Any help would be greatly appreciated :)

**Comment by bnfinet** [comment]
I won't be able to look at this closely until the new year but I'll try to
chime in...

502 probably means nginx can't see lasso upstream.

Is nginx in a separate container of it's own?  Can the nginx reach lasso
at...
http://127.0.0.1:9090/validate


Best of luck

**Comment by joshkay** [comment]
Thanks for the quick response!  No rush at all.

They are both running in separate containers.  How can I test if nginx can reach that url?

I can go to login.REDACTED_URL/login and it shows `/login no destination URL requested.`, so the reverse proxy seems to be working properly.

**Comment by bnfinet** [comment]
Okay, took a quick look here, it looks like there's something wrong with your config.  Is `oauth.provider` set?

Did you start with one of the basic configs?  
https://github.com/LassoProject/lasso/blob/master/config/config.yml_example_google

can you please post your (redacted) `config.yml`

**Comment by joshkay** [comment]
I was trying to authenticate using oidc after following a tutorial.  I scrapped that config and tried from scratch using google auth.  It works properly when I set `allowAllUsers` to true, but when I set it to false with a whitelist for my google email it doesn't load with a `redirected you too many times.` error.

Seems like I'm having the same issue as https://github.com/LassoProject/lasso/issues/42

```
lasso:
  domains:
  - REDACTED_URL
  whiteList:
  - REDACTED_EMAIL
oauth:
  provider: google
  client_id: REDACTED
  client_secret: REDACTED
  callback_urls: 
    - https://login.REDACTED_URL/auth
```

**Comment by bnfinet** [comment]
I am personally running a config that is identical to the one that you have presented.

Does `lasso.domains[0]` represent a domain present in `oauth.callback_urls[0]`?  And, is the domain that lasso is running at present in `lasso.domains[0]`?  (should be since that's your callback).

The lasso jwt is getting set as a cookie into `lasso.domains[0]` so any site that is protected by lasso needs to be within that domain.

here's my config...
```
# lasso config
# bare minimum to get lasso running with google

lasso:
  # domains:
  # each of these domains must serve the url https://login.$domains[0] https://login.$domains[1] ...
  # the callback_urls will be to these domains
  domains:
  - bnf.net
 
  whitelist:
  - me@bnf.net
  - someone@gmail.com
  - someoneelse@their.com

oauth:
  # create credentials at:
  # https://console.developers.google.com/apis/credentials
  provider: google
  client_id: myid
  client_secret: mysecret
  callback_urls: 
    - https://login.private.bnf.net/auth
```

and all the sites which are protected by lasso are within `*.private.bnf.net`

Happy  New Year and good hacking!

**Comment by joshkay** [comment]
Happy New Year to you too!  Thanks so much for all of the help so far.

My domain is essentially `domainname.com` and my callback url is `https://login.domainname.com/auth`.  So the domain is present in the callback_url.

The domain that lasso is running at is `https://login.domainname.com`.  Is that the correct setup?

**Comment by bnfinet** [comment]
Is allowAllUsers set in your config?  It would appear that it is not.

**Comment by bnfinet** [comment]
And to be clear, it no longer panics at startup, is that right?

**Comment by bnfinet** [comment]
My guess is that there's some problem with setting and then reading the cookie back from the domain.

Is https://login.domainname.com behind the same nginx revproxy?  Does login.domainname.com enforce login to lasso? (it shouldn't)

If you go to https://login.domainname.com/validate what does it say?

Try changing your nginx config to use `proxy_pass http://127.0.0.1:9090` instead of `proxy_pass http://127.0.0.1:9090/validate`

Try adding `internal;` to the `location = /validate {` block

Try setting `lasso.testing: true`
https://github.com/LassoProject/lasso/blob/master/config/config.yml_example#L67
That will force manual click through instead of 302 redirect and may help you to discern the problem.

**Comment by joshkay** [comment]
https://login.domainname.com is behind its own nginx revproxy.  Here's the server config for it:

```
server {
    listen 443 ssl;
    server_name login.domainname.com;

    ssl_certificate /etc/letsencrypt/live/login.domainname.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/login.domainname.com/privkey.pem;

    # Proxy to your Lasso instance
    location / {
      proxy_set_header  Host  login.domainname.com;
      proxy_set_header  X-Forwarded-Proto https;
      proxy_pass        http://192.168.10.32:9090;
    }
  }
```

If I go to https://login.domainname.com/validate it says `no jwt found in request`.

I tried changing the `proxy_pass` and adding `internal`, but that seems to change nothing.

I feel as though I am missing something very simple.  After setting testing to true I can see that it is just bouncing back and forth between https://domainname.com and the google auth.

- https://accounts.google.com/o/oauth2/auth?client_id=REDACTEDhd=&redirect_uri=https%3A%2F%domainname.com%2Fauth&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=hRotjGPRFLAkGF0p%2BrXmyaX914RuOk5g14ZJ%2F6uTV%2Bk%3D
- https://domainname.com
- https://accounts.google.com/o/oauth2/auth?client_id=REDACTEDhd=&redirect_uri=https%3A%2F%domainname.com%2Fauth&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=hRotjGPRFLAkGF0p%2BrXmyaX914RuOk5g14ZJ%2F6uTV%2Bk%3D
- https://domainname.com

The authorized redirect URL is set to https://login.domainname.com/auth
Is that correct?

**Comment by bnfinet** [comment]
Yes that looks correct.

What browser are you using?

If you go into Developer Tools and look at the Cookies do you see a cookie named "LassoCookie" set into the Domain ".domainname.com"?

**Comment by joshkay** [comment]
Using chrome.

Don't see that cookie.  Only lasso session on https://login.domainname.com

**Comment by bnfinet** [comment]
With testing on, do you see a header to set the cookie?

**Comment by joshkay** [comment]
When I first try go to https://domainname.com with test mode on I am greeted with the redirect to `https://accounts.google.com/o/oauth2/auth?client_id=REDACTEDhd=&redirect_uri=https%3A%2F%2Flogin.domainname.com%2Fauth&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=ScW4kVlOfRXYR0tYX3XGRkPXOAwMTO1X9DFoDqJAWIc%3D.`

There's a header to delete the cookie there:
`set-cookie: LassoCookie=delete; Path=/; Domain=domainname.com;`

I then proceed with the redirect and login with google.  Then it redirects me to https://domainname.com.

There's a header to set the cookie there:
set-cookie: LassoCookie=REDACTED; Path=/; Domain=domainname.com; Max-Age=14400; HttpOnly
set-cookie: lassoSession=REDACTED; Path=/; Expires=Sat, 05 Jan 2019 00:03:47 GMT; Max-Age=300

When I proceed with the redirect to https://domainname.com the cookie is passed along in the request as well.  It still redirects me to login again however.

**Comment by joshkay** [comment]
Got it working!  There was an issue with my nginx config.

I added `proxy_set_header X-Lasso-User $auth_resp_x_lasso_user;` to my location.
I replaced my validate location with the one in the README.
I also set my proxy_pass to `proxy_pass https://login.domainname.com/validate;` instead of the IP.

Thank you very much for all of your help!

**Comment by big-kahuna-burger** [comment]
@joshkay Could you share your complete config in a gist (nginx and lasso) with redacted domain names and variables for comparison?

**Comment by bnfinet** [comment]
You are very welcome @joshkay .  Hope it's smooth sailing from here on.

Please do offer your correct config here (HT @big-kahuna-burger)

closing
