### ISSUE TITLE
Flexible structures?

### ISSUE THREAD

**Issue by big-kahuna-burger** [LassoProject/lasso#45]
Any idea how to approach this with configurable storage/model/structures? 
I've configured this almost all the way but I have problem with `user.Id` being int...

**Comment by bnfinet** [comment]
`User.ID` is a primary key set from a sequence number generated by the db (`boltdb`) at..
https://github.com/LassoProject/lasso/blob/master/pkg/model/user.go#L34-L35

`User.Username` carries the text user handle (often an email address)

What's your desire for modifying user.Id?  What would you like to accomplish?

Happy New Year and Happy Hacking!

**Comment by big-kahuna-burger** [comment]
I haven't read whole source, got some error here related to being `impossible to marshal _something_ into _something_`, which I thought of as problem related to what I return from our OAuth2 `/userinfo` endpoint. Point being here, is that I've used generic oidc config with our own oidc provider.

Anyway, thanks for your help!

**Comment by bnfinet** [comment]
can I ask which OIDC provider you're using?

**Comment by big-kahuna-burger** [comment]
We are implementing it ourselves (myself to be precise) using `oauth2orize`. While it is ok to implement it with oauth2orize, my idea is to switch in future to panva's [node-oidc-provider](https://github.com/panva/node-oidc-provider), since it's OIDC compliant/certified.
